require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/*_schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - 'app/services/**/*.rb'

Rails/NotNullColumn:
  Enabled: false