services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_DATABASE: popmenu_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USER: rails
      DB_PASSWORD: secret
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
